<?php defined('KRYSTAL') or die; ?>
<form>
 <textarea data-wysiwyg="true" name="content"><?php echo $content; ?></textarea>
 
 <br />
 <button data-button="save" data-url="<?php echo $this->url('AboutBox:Admin:Config@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
 <button data-button="cancel" data-url="<?php echo $this->url('Cms:Admin:Dashboard@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
 
</form>